services:
  - type: web
    name: attendance-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y chromium chromium-driver
      pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/chromium
